Fix/dst/double jump
SonTonyD/Project-DNA pull request #10
Opened 2022-12-30 19:34 UTC by SonTonyD

---
name: Pull request
about: Fix double jump
title: Fix
assignees: Dinh-SM, SonTonyD

---

# **Describe the changes**

> Please check one or more that apply to this pull request

* [ ] Feature
* [x] Bug fix
* [ ] Refactor (no functional changes)
* [ ] Other (include details)

> What has changed and how did you do it?

> The bug -> The player model was stuck in a specific position when it starts the second jump during jump land animation.
> The solution -> Add of a raycast under the player model to prevent the player from starting a second jump when it is too close to the ground 

# **References**

The additional resources you used.

2022-12-30 23:15 UTC, Dinh-SM requested changes

2022-12-30 23:15 UTC, Dinh-SM commented on Assets/Scripts/InputHandler.cs
> -
Was it used somewhere else to be made a property ?

2022-12-30 23:15 UTC, Dinh-SM commented on Assets/Scripts/PlayerMovement.cs
> +
The above code needs to be moved inside the second jump `else if` block, otherwise the raycast hit is always calculated whether we do the first or second jump -> not optimized.
Also, remove or comment the `Debug.DrawLine` line because it also impact the performance.

2022-12-30 23:16 UTC, Dinh-SM requested changes

2022-12-30 23:16 UTC, Dinh-SM commented on Assets/Scripts/InputHandler.cs
> +        public PlayerControl InputActions { get => _inputActions; set => _inputActions = value; }
Was it used somewhere else to be made a property ?

2022-12-30 23:17 UTC, Dinh-SM commented on Assets/Scripts/PlayerMovement.cs
> +
[ ] To move

2022-12-30 23:59 UTC, SonTonyD commented on Assets/Scripts/InputHandler.cs
> +        public PlayerControl InputActions { get => _inputActions; set => _inputActions = value; }
Yes, I forgot to remove this line. It is done now.

2022-12-31 00:08 UTC, SonTonyD commented on Assets/Scripts/PlayerMovement.cs
> +
Ok, now the raycast hit should only be calculated if the jump input is active, the player is not on the ground and didSecondJump is false.

2022-12-31 09:23 UTC, Dinh-SM approved these changes

2022-12-31 09:23 UTC, merged